### ISSUE TITLE
Local fresh build produces empty image output

### ISSUE THREAD

**Issue by doodlewind** [Brooooooklyn/skia-rs#120]
Hi, I'm trying to build and run this project locally, the `libskia.a` and the `skia.node` addon can be successfully built, but for the `simple` and `tiger` examples, I can only get transparent images as output.

Commands I used for building:

``` sh
$ git clone --recurse-submodules https://github.com/Brooooooklyn/skia-rs.git
$ cd skia-rs
$ node scripts/build-skia.js
$ yarn install
$ npm run build
```

And commands for testing:

``` sh
$ npm test # success
$ node examples/simple.js # blank image
$ node examples/tiger.js # blank image
```

It's worth to note that during `yarn install`, the `canvas` dependency installation fails on the final `node-pre-gyp` build stage (both on WSL2 and macOS 10.15). I believe other dependencies are installed correctly.

`simple.png`:

![simple](https://user-images.githubusercontent.com/7312949/103744591-03150800-5039-11eb-9895-15a3d031c068.png)

`tiger.png`:

![tiger](https://user-images.githubusercontent.com/7312949/103744616-0e683380-5039-11eb-8cc6-9aa19daf0204.png)

I've tried on WSL2 and macOS and got the same output result, wondering if I'm missing some configurations :(

**Comment by Brooooooklyn** [comment]
It should be fixed in `snapshot-test` branch, please checkout to `snapshot-test` and try again :)

**Comment by doodlewind** [comment]
Works now, it's very impressive that the `.png` outputs can reach byte-level consistency with the ones stored in git, thanks!
